### ISSUE TITLE
cgrp instruments do not work from within docker

### ISSUE THREAD

**Issue by thrau** [edgerun/telemd#12]
running telemd in a container without disabling cgrp_cpu and cgrp_blkio  will result in a panic:

```
panic: open /sys/fs/cgroup/blkio/docker: no such file or directory

goroutine 82 [running]:
github.com/edgerun/telemd/internal/telemd.listFilterDir(0x723f52, 0x1b, 0x72e078, 0x200, 0x0, 0x0)
	/go/src/github.com/edgerun/go-telemd/internal/telemd/cfg.go:126 +0x265
github.com/edgerun/telemd/internal/telemd.CgroupBlkioInstrument.MeasureAndReport(0x76df20, 0xc0000bc0f0)
	/go/src/github.com/edgerun/go-telemd/internal/telemd/instrument.go:277 +0x57
created by github.com/edgerun/telemd/internal/telemd.(*telemetryTicker).Run
	/go/src/github.com/edgerun/go-telemd/internal/telemd/ticker.go:62 +0x288
```

**Comment by phip123** [comment]
CPU and BLKIO are working but as stated in the README, the net instrument does not work due to alpine using musl.
